### ISSUE TITLE
open3d 의 visualization 실행 오류

### ISSUE THREAD

**Issue by Young95K** [reconlabs-kawatani/ms_remove_pp#5]
- [x] MR3 외부 스크립트에서 open3d 라이브러리 사용하여 `capture_screen_image` 수행
- [x] 동일 환경에서 `capture_depth_float_buffer` 수행하여 depth map export 테스트

**Comment by Young95K** [comment]
@reconlabs-kawatani 근데 제가 기존에 작성한 이슈랑 좀 겹치는것 같은데 어떻게 하는게 좋을지 내일 상의 하거나/팁 전수 해주세요.

**Comment by reconlabs-kawatani** [comment]
@Young95K 그래서 사실 아까 미리 태스크라는 용어를 정확히 알려드린겁니다. 태스크는 단순히 해야할 일의 의미라기 보다는, 더 이상 쪼갤 수 없는 단위의 해야 할 일 이라고 보통 정의합니다. 저는 이슈를 최대한으로 적은 수의 태스크만 포함하게 잡습니다. 그러면 중복 될 일이 크게 없기도 하고, 익숙해지면 중복이 될 거 같은데 하고 예상되는 짬바(?)가 생깁니다.  

지금 만드신 이슈는 최소 단위로 잘 정의하신 것 같습니다.

**Comment by Young95K** [comment]
넵 차차 태스크 개념에 더 익숙해질것 같네요. 감사합니다.

**Comment by Young95K** [comment]
![image](https://user-images.githubusercontent.com/123041953/223913757-17d39209-ff36-4086-8f18-b769a0989382.png)
1. install latest cmake
2. build open3d [master (f2ae73d)]
3. not working
@reconlabs-kawatani  뭘까요..

**Comment by reconlabs-kawatani** [comment]
> 

cmake를 할때 저 옵션을 안주고 make install을 해서 발생한 것 같습니다. 저 예시 코드는 저는 잘 동작합니다.

**Comment by Young95K** [comment]
승민님이 성공해보셨어서 참 다행이네요.
http://www.open3d.org/docs/latest/tutorial/Advanced/headless_rendering.html#install-osmesa
![image](https://user-images.githubusercontent.com/123041953/223918722-0ef1f56f-f5e0-4114-b33d-eae3f60e84ab.png)
저는 그래서 여기 나온 옵션들 포함하여 다시 CMake 중입니다.

**Comment by Young95K** [comment]
![image](https://user-images.githubusercontent.com/123041953/223926285-bacaaa48-478a-47dd-bbee-c278bc391bc8.png)
그래도 안되네요...

**Comment by Young95K** [comment]
@leo-recon @reconlabs-kawatani 시간 되시는 분 계시면 도움을 요청합니다.. 저는 `headless_rendering.py` 계속 실패하네요.

**Comment by Young95K** [comment]
- 위 실패 사례들에서는 virtualenv 설정하지 않고, MR3 설치할 당시에 깔려있던 open3d 이미 존재하는 상태에서 cmake 시도했음.
- python virtualenv 내부에서 cmake를 통한 install 시도했음.
- `make install-pip-package` 스크립트에서 아래 오류 발생:
```WARNING: Skipping open3d as it is not installed.
ERROR: open3d_cpu-0.17.0+88693971a-cp38-cp38-manylinux_2_31_x86_64.whl is not a supported wheel on this platform.```
- 그리고 당연하게도 import open3d 안됨.

**Comment by Young95K** [comment]
```WARNING: Skipping open3d as it is not installed.
ERROR: open3d-0.15.1+ed30e3b61-cp38-cp38-manylinux_2_31_x86_64.whl is not a supported wheel on this platform.
```
v0.15.1 도 나가리입니다ㅠ

**Comment by leo-recon** [comment]
@Young95K 제가 아직은 깃헙 커뮤니케이션이 어색해서 지금 봤습니다. 사용하시는 클라우드의 os (ubuntu 버전?) 정보등을 아는대로 알려 주실 수 있을까요?

**Comment by Young95K** [comment]
**gcp a100** 
![image](https://user-images.githubusercontent.com/123041953/223956992-eee8f820-1f4f-47fd-a179-a92923d2477b.png)
입니다!

**Comment by leo-recon** [comment]
@reconlabs-kawatani 도움이 되실지 모르겠네요.

https://github.com/isl-org/Open3D/blob/master/examples/python/camera/camera_trajectory.py

카메라 파라미터 관련 쏘스코드를 좀 보려고 했는데 못 찾고 위 예제를 찾았습니다.
 너무 많은 방법이 있겠지만 io 관련한 부분있어서 공유 드립니다

**Comment by reconlabs-kawatani** [comment]
> 

저 examples 안에 유용한 정보가 일단 많은 것 같긴 합니다.

**Comment by Young95K** [comment]
답은 pip upgrade 였답니다. @.@
`python -m pip install --upgrade pip`
